# Lighthouse CI Configuration
# This file helps you monitor performance over time

ci:
  collect:
    url:
      - http://localhost:3000
    numberOfRuns: 3
    settings:
      preset: 'mobile'
      throttling:
        cpuSlowdownMultiplier: 4
        rttMs: 150
        throughputKbps: 1638
        requestLatencyMs: 150
        downloadThroughputKbps: 1638
        uploadThroughputKbps: 768
  assert:
    preset: 'lighthouse:recommended'
    assertions:
      # Core Web Vitals
      'first-contentful-paint':
        - error
        - maxNumericValue: 1800 # 1.8s
      'largest-contentful-paint':
        - error
        - maxNumericValue: 2500 # 2.5s
      'cumulative-layout-shift':
        - error
        - maxNumericValue: 0.1
      'total-blocking-time':
        - error
        - maxNumericValue: 200 # 200ms
      'speed-index':
        - error
        - maxNumericValue: 3400 # 3.4s
      
      # Performance Score
      'categories:performance':
        - error
        - minScore: 0.7 # 70+
  upload:
    target: 'temporary-public-storage'
